In [1]:
# Cell 1
# Q1

import numpy as np

A = np.arange(1, 21).reshape(4, 5)

print("A =\n", A)
print("dtype =", A.dtype)
print("ndim =", A.ndim)
print("shape =", A.shape)
print("size =", A.size)
print("itemsize =", A.itemsize)

B = A.reshape(5, 4)

print("B =\n", B)

A =
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
dtype = int64
ndim = 2
shape = (4, 5)
size = 20
itemsize = 8
B =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [2]:
# Cell 2
# Q2

import numpy as np

a = np.array([[0.,0.,0.,0.],
              [10.,10.,10.,10.],
              [20.,20.,20.,20.],
              [30.,30.,30.,30.]])

b = np.array([0.,1.,2.,1.])

c = a + b

print("c =\n", c)

mask = (c >= 22)

print("mask =\n", mask)

count = np.sum(c >= 22)

print("Count =", count)

c =
 [[ 0.  1.  2.  1.]
 [10. 11. 12. 11.]
 [20. 21. 22. 21.]
 [30. 31. 32. 31.]]
mask =
 [[False False False False]
 [False False False False]
 [False False  True False]
 [ True  True  True  True]]
Count = 5


In [3]:
# Cell 3
# Q3

import numpy as np

grades = np.array([[87, 96, 70],
                   [100, 87, 90],
                   [94, 77, 90],
                   [100, 81, 82]])

print("Sum =", grades.sum())
print("Min =", grades.min())
print("Max =", grades.max())
print("Mean =", grades.mean())
print("Std =", grades.std())
print("Var =", grades.var())

print("Mean per column =", grades.mean(axis=0))
print("Mean per row =", grades.mean(axis=1))
print("Max per row =", grades.max(axis=1))

Sum = 1054
Min = 70
Max = 100
Mean = 87.83333333333333
Std = 8.792357792739987
Var = 77.30555555555556
Mean per column = [95.25 85.25 83.  ]
Mean per row = [84.33333333 92.33333333 87.         87.66666667]
Max per row = [ 96 100  94 100]


In [4]:
# Cell 4
# Q4

import numpy as np

A = np.array([[2, 4, 6],
              [1, 3, 5],
              [7, 9, 11]])

print("Sum of each row =", A.sum(axis=1))
print("Sum of each column =", A.sum(axis=0))
print("Overall mean =", A.mean())

Sum of each row = [12  9 27]
Sum of each column = [10 16 22]
Overall mean = 5.333333333333333


In [5]:
# Cell 5
# Q5

import numpy as np

A = np.array([[10, 20, 30],
              [40, 50, 60]])

B = np.array([1, 2, 3])

print("A + B =\n", A + B)

print("A * 2 =\n", A * 2)

print("A - 5 =\n", A - 5)

A + B =
 [[11 22 33]
 [41 52 63]]
A * 2 =
 [[ 20  40  60]
 [ 80 100 120]]
A - 5 =
 [[ 5 15 25]
 [35 45 55]]


In [6]:
# Cell 6
# Q6

import numpy as np

grades = np.array([[70, 85, 90],
                   [88, 76, 95],
                   [60, 80, 72]])

print("Index of largest value =", np.argmax(grades))

print("Index of highest grade in each row =",
      np.argmax(grades, axis=1))

print("Index of lowest grade in each column =",
      np.argmin(grades, axis=0))

Index of largest value = 5
Index of highest grade in each row = [2 2 1]
Index of lowest grade in each column = [2 1 2]


In [7]:
# Cell 7
# Q7

import numpy as np

def manhattan_distance(x1, y1, x2, y2):
    return abs(x2 - x1) + abs(y2 - y1)

def euclidean_distance(x1, y1, x2, y2):
    return np.sqrt((x2 - x1)**2 + (y2 - y1)**2)

print("Manhattan Distance =",
      manhattan_distance(1, 2, 4, 6))

print("Euclidean Distance =",
      euclidean_distance(1, 2, 4, 6))

Manhattan Distance = 7
Euclidean Distance = 5.0


In [8]:
# Cell 8
# Part 2 - Q1

import numpy as np

table = np.array([[5, 8, 2, 7],
                  [1, 9, 4, 3],
                  [6, 0, 11, 10],
                  [12, 13, 14, 15]])

print("Second row =", table[1])

print("Third column =\n", table[:, 2])

print("Sub-table =\n", table[1:3, 1:3])

Second row = [1 9 4 3]
Third column =
 [ 2  4 11 14]
Sub-table =
 [[ 9  4]
 [ 0 11]]


In [9]:
# Cell 9
# Part 2 - Q2

import numpy as np

scores = np.array([[70, 80, 90],
                   [60, 75, 85],
                   [88, 92, 79],
                   [55, 65, 72]])

scores[:, 1] += 5
print("After increasing Physics marks:\n", scores)

scores[0] = [100, 100, 100]
print("After replacing first student marks:\n", scores)

scores[:, 2] = 0
print("After setting CS column to zero:\n", scores)

After increasing Physics marks:
 [[70 85 90]
 [60 80 85]
 [88 97 79]
 [55 70 72]]
After replacing first student marks:
 [[100 100 100]
 [ 60  80  85]
 [ 88  97  79]
 [ 55  70  72]]
After setting CS column to zero:
 [[100 100   0]
 [ 60  80   0]
 [ 88  97   0]
 [ 55  70   0]]


In [10]:
# Cell 10
# Part 2 - Q3

import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

v = np.array([2, 4])

print("Element-wise multiplication:\n", A * B)

print("Matrix multiplication:\n", A @ B)

print("Broadcasting:\n", A * v)

Element-wise multiplication:
 [[ 5 12]
 [21 32]]
Matrix multiplication:
 [[19 22]
 [43 50]]
Broadcasting:
 [[ 2  8]
 [ 6 16]]


In [11]:
# Cell 11
# Part 2 - Q4(A)

import numpy as np

np.random.seed(0)

matrix = np.random.randint(-5, 6, size=(4, 4))

print("Matrix =\n", matrix)

unique_values, counts = np.unique(matrix, return_counts=True)

print("Unique values =", unique_values)

print("Counts =", counts)

unique_rows = np.unique(matrix, axis=0)

print("Unique rows =\n", unique_rows)

Matrix =
 [[ 0 -5 -2 -2]
 [ 2  4 -2  0]
 [-3 -1  2  1]
 [ 3  3  5 -4]]
Unique values = [-5 -4 -3 -2 -1  0  1  2  3  4  5]
Counts = [1 1 1 3 1 2 1 2 2 1 1]
Unique rows =
 [[-3 -1  2  1]
 [ 0 -5 -2 -2]
 [ 2  4 -2  0]
 [ 3  3  5 -4]]


In [12]:
# Cell 12
# Part 2 - Q4(B)

import numpy as np

a = np.array([[1, 0, 0],
              [1, 0, 0],
              [2, 3, 4]])

unique_rows = np.unique(a, axis=0)

print("Unique rows =\n", unique_rows)

Unique rows =
 [[1 0 0]
 [2 3 4]]


In [13]:
# Cell 13
# Part 2 - Q5

import numpy as np

x = np.array([2, 0, 1, 5, 4, 1, 9])

A = np.array([[3, 8, 1],
              [6, 2, 9]])

indices = np.argsort(x)

print("Indices after sorting =", indices)

print("Sorted x =", x[indices])

min_location = np.unravel_index(A.argmin(), A.shape)

print("Minimum value location =", min_location)

print("Indices where x > 3 =", np.where(x > 3))

parts = np.split(x, [2, 5])

print("First part =", parts[0])
print("Second part =", parts[1])
print("Third part =", parts[2])

x_expanded = np.expand_dims(x, axis=0)

print("Expanded shape =\n", x_expanded)

x_squeezed = np.squeeze(x_expanded)

print("Squeezed array =", x_squeezed)

Indices after sorting = [1 2 5 0 4 3 6]
Sorted x = [0 1 1 2 4 5 9]
Minimum value location = (np.int64(0), np.int64(2))
Indices where x > 3 = (array([3, 4, 6]),)
First part = [2 0]
Second part = [1 5 4]
Third part = [1 9]
Expanded shape =
 [[2 0 1 5 4 1 9]]
Squeezed array = [2 0 1 5 4 1 9]
